### ISSUE TITLE
 This is awsome. Do you need any help?

### ISSUE THREAD

**Issue by catskul** [LinusCDE/rmTabletDriver#2]
Happy to contribute development effort if any is needed for this project.

**Comment by LinusCDE** [comment]
Hi.  
Thank you for your kind question.

As you may see, I'm not actively working on this project anymore. After I got it to work, I was basically done with it.

One thing that was on my todo list and never got done is implementing support for LibInput. I had looked into their source code and figured, that I needed to add the resolution. That was the reason for adding a c implementation since, the python library didn't assign it at that time. But after I added the resolution, the fake device was only ever recognized as a keyboard (never figured out why).

I had also toyed with the idea of trying out a windows (userspace) driver. But I'm not actively using Windows and never found the time, too.

Another thing could be to a some kind of UI to make the setup easier. Editing the xorg file, installing the configurator and so on is not really suited for the people that could take the most advantage out of the tech.

There really also isn't a reason to use UDP instead of TCP for this and the other project.

You see there are quite some things. I currently have some projects for work and university (also partly work). And my current side project passion lies in configuring WireGuard, Iptables, Nginx and services with docker in general (so more sys admin work).

If you want, I can add you as a contributor if desired.

Thank you for your interest in this project.
If you need anything further, just ask. Depending on the activity of contributions, you could also take over the whole project.

**Comment by catskul** [comment]
Going to try to get it running on my reMarkable this evening. Once I've got it running I'll look into seeing if I'm into trying any of those changes.

**Comment by LinusCDE** [comment]
Cool. 😃

**Comment by catskul** [comment]
Got your code up and running a few evenings ago and it works great.

Got the reMarkable Qt creator development environment working, and Draft, button interceptor and such running.

Also have a bunch of reading material on libwacom and libinput.

Should have some progress tomorrow now that I have everything set up.

**Comment by LinusCDE** [comment]
Great!
I had considered using libwacom, but I don't have much experience with c libraries and didn't find a applicable way to create a dummy device, that could show up in wacom device configurators.  
Getting that to work would be to good to be true!

I also have not much experience with QT (and C++ for that matter). I'm currently diving into Rust.
