### ISSUE TITLE
How can I only enable the tablet driver in GIMP

### ISSUE THREAD

**Issue by Toorero** [LinusCDE/rmTabletDriver#3]
I've installed everything properly as you described as well as calibrating it accordingly, but I'm using libinput and it seems to work great. But sadly I'm unable to use the driver in GIMP because there are actually "two mousepointers" present now. One regular mouse pointer from the tablet and one only seen if I'm in the GIMP working canvas, but sadly off-centre from the other one. Is there any way to disable the normal mouse pointer all together and only enable the tablet in GIMP?

**Comment by LinusCDE** [comment]
I think you can disable the normal mouse which is called the "Core pointer". I found the behaviour in gimp fairly odd as well. Needed to try a lot and use the pen itself to change it's brush. Seems that depending on which is moved last, gimp has two separate profiles/settings (similar like how games change the keymap as soon as you use the other input device).

So:
 - Did you checkout the "Edit -> Input devices" dialog?
 - Did you try to select a brush with the pen itself?

Otherwise I'm not really sure what the problem is. Gimp just seems a bit finicky in general. My best out-of-the-box experience yet was testing with Xournal.

**Comment by Toorero** [comment]
Thanks for your kind answer. I tried Xournal(pp) and really works great. Sadly there is no pressure support in GIMP or Krita yet...

I managed to fix my described error **by switching in GIMP from Window mode to the Screen mode in "Edit -> Input devices**.

 Thanks for that amazing driver!
